package:
  - path: c:\pkginfo.json
    content: |
      {
        "environment": {
          "MESOS_IP_DISCOVERY_COMMAND": "c:\\opt\mesosphere\\bin\\detect_ip.ps1",
          "PROVIDER": "{{ provider }}"
        }
      }
  - path: c:\etc\mesosphere\setup-flags\repository-url
    permissions: "0644"
    content: |
      {{ bootstrap_url }}
  - path: c:\etc\mesosphere\setup-flags\cluster-package-list
    permissions: "0644"
    content: |
      {{ cluster_package_list_id }}
  - path: /etc/mesos-slave-modules/overlay_slave_modules.json
    content: |
      {
        "libraries":
        [
          {
            "file": "/opt/mesosphere/active/mesos-modules/lib/mesos/libmesos_network_overlay.so",
            "modules":
              [
                {
                  "name": "com_mesosphere_mesos_OverlayAgentManager",
                  "parameters" :
                    [
                      {
                        "key": "agent_config",
                        "value" : "/opt/mesosphere/etc/overlay/config/agent.json"
                      }
                    ]
                }
              ]
           }
        ]
      }
{% case "false" %}
{% endswitch %}
  - path: /etc/mesos-slave-modules/metrics.json
    content: |
      {
        "libraries": [ {
          "file": "/opt/mesosphere/active/mesos-modules/lib/mesos/libmetrics-module.so",
          "modules": [ {
            "name": "com_mesosphere_dcos_MetricsIsolatorModule",
            "parameters": [
              {"key": "dcos_metrics_service_scheme", "value": "http"},
              {"key": "dcos_metrics_service_network", "value": "unix"},
              {"key": "dcos_metrics_service_address", "value": "/run/dcos/telegraf/dcos_statsd.sock"},
              {"key": "dcos_metrics_service_endpoint", "value": "/container"}
            ]
          } ]
        } ]
      }
  - path: /etc/mesos-slave-modules/journal_logger_modules.json
    content: |
      {
        "libraries": [
          {
            "file": "/opt/mesosphere/active/mesos-modules/lib/mesos/libjournaldlogger.so",
            "modules": [
              {
                "name": "com_mesosphere_mesos_JournaldLogger",
                "parameters": [
                  {
                    "key": "destination_type",
                    "value": "{{ mesos_container_log_sink }}"
                  }, {
                    "key": "companion_dir",
                    "value": "/opt/mesosphere/active/mesos-modules/bin/"
                  }, {
                    "key": "libprocess_num_worker_threads",
                    "value": "2"
                  }, {
                    "key": "logrotate_max_stdout_size",
                    "value": "2MB"
                  }, {
                    "key": "logrotate_stdout_options",
                    "value": "rotate 9"
                  }, {
                    "key": "logrotate_max_stderr_size",
                    "value": "2MB"
                  }, {
                    "key": "logrotate_stderr_options",
                    "value": "rotate 9"
                  }, {
                    "key": "fluentbit_ip",
                    "value": "127.0.0.1"
                  }, {
                    "key": "fluentbit_port",
                    "value": "61092"
                  }
                ]
              }
            ]
          }
        ]
      }
{% switch dcos_remove_dockercfg_enable %}
{% case "true" %}
  - path: /etc/mesos-slave-modules/remove_dockercfg_slave_modules.json
    content: |
      {
        "libraries":
        [
          {
            "file": "/opt/mesosphere/active/mesos-modules/lib/mesos/libremovedockercfg.so",
            "modules":
              [
                {
                  "name": "com_mesosphere_dcos_RemoverHook"
                }
              ]
           }
        ]
      }
{% case "false" %}
{% endswitch %}
  - path: /etc/mesos-slave-dns.json
    content: |
      {
        "docker":
        [
            {
              "network_mode": "USER",
              "dns": {
                "nameservers": [
{% switch enable_ipv6 %}
{% case "true" %}
                                "198.51.100.1",
                                "fd01:d::c633:6401"
{% case "false" %}
                                "198.51.100.1"
{% endswitch %}
                ]
              }
            }
        ]
      }
  - path: /etc/mesos-slave-image-gc-config.json
    content: |
      {
        "image_disk_headroom": 0.1,
        "image_disk_watch_interval": {
          "nanoseconds": 300000000000
        },
        "excluded_images": []
      }
